- VirtoCommerce.StoreModule.Data/Services/StoreServiceImpl.cs
- VirtoCommerce.StoreModule.Data/Services/Validation/StoreValidator.cs
- VirtoCommerce.StoreModule.Data/VirtoCommerce.StoreModule.Data.csproj
- VirtoCommerce.StoreModule.Data/packages.config
- VirtoCommerce.StoreModule.Test/App.config
- VirtoCommerce.StoreModule.Test/StoreControllerTest.cs
- VirtoCommerce.StoreModule.Test/StoreControllerUnitTest.cs
- VirtoCommerce.StoreModule.Test/VirtoCommerce.StoreModule.Test.csproj
- VirtoCommerce.StoreModule.Test/packages.config
- VirtoCommerce.StoreModule.Web/Localizations/de.VirtoCommerce.Store.json
- VirtoCommerce.StoreModule.Web/Localizations/en.VirtoCommerce.Store.json
- VirtoCommerce.StoreModule.Web/Scripts/wizards/newStore/new-store-wizard.js
- VirtoCommerce.StoreModule.Web/Scripts/wizards/newStore/new-store-wizard.tpl.html
#6 Add validation for store code
> #6 add validation for code

- VirtoCommerce.StoreModule.Web/Scripts/blades/store-detail.js
- VirtoCommerce.StoreModule.Web/Scripts/blades/store-detail.tpl.html
- VirtoCommerce.StoreModule.Web/Scripts/store.js
https://app.assembla.com/spaces/heineken-nigeria/tickets/realtime_cardwall?ticket=63
> Added ability using metaform in edit store blade

- VirtoCommerce.StoreModule.Web/Localizations/en.VirtoCommerce.Store.json
- VirtoCommerce.StoreModule.Web/Scripts/blades/loginOnBehalf/loginOnBehalf-list.js
- VirtoCommerce.StoreModule.Web/Scripts/dialogs/enter-store-url-dialog.js
- VirtoCommerce.StoreModule.Web/Scripts/dialogs/enter-store-url-dialog.tpl.html
- VirtoCommerce.StoreModule.Web/VirtoCommerce.StoreModule.Web.csproj
- Added form allowing enter store URL when it is not defined;
> #1518 Allow to login on behalf without defined url for stores:

- VirtoCommerce.StoreModule.Web/module.manifest
- Added settings "Stores.AllowAnonymousUsers" (true by default), which is used to check if anonymous user allowed for the store on storefront;
> #220 Add an option to disable anonymous user in storefront:

- VirtoCommerce.StoreModule.Data/Services/StoreServiceImpl.cs
> Paged search ordering revision

- VirtoCommerce.StoreModule.Data/Repositories/StoreRepositoryImpl.cs
Query optimization refactoring
> Query optimization based on collection emptiness

- VirtoCommerce.StoreModule.Web/JsonConverters/PolymorphicStoreJsonConverter.cs
> add check of shipping method type

- src/VirtoCommerce.StoreModule.Data/Handlers/LogChangesChangedEventHandler.cs
- src/VirtoCommerce.StoreModule.Web/Module.cs
To invalidate the storefront cache when the store have been changed.
> VP-1494 Add LogChangesChangedEventHandler

- VirtoCommerce.StoreModule.Web/Scripts/blades/store-advanced.js
- VirtoCommerce.StoreModule.Web/Scripts/blades/store-advanced.tpl.html
fix for https://github.com/VirtoCommerce/vc-module-store/issues/28
> add server-side filter for fulfillment centers

- src/VirtoCommerce.StoreModule.Data/Repositories/StoreRepository.cs
> VP-0: Make GetStoresByIdsAsync virtual

- src/VirtoCommerce.StoreModule.Data/Services/StoreService.cs
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
A clear and concise description of what you want to happen.
Describe the technical details of realization provided by you.
Add any other context or screenshots about the feature request here.
> VP-5334: Call ClearCache before publish event

- src/VirtoCommerce.StoreModule.Web/Scripts/blades/store-detail.js
- src/VirtoCommerce.StoreModule.Web/Scripts/blades/store-detail.tpl.html
VP-6104 Store > Catalog dropdown > Some catalogs are not uploaded
Drop down do not uploads more than 40 catalogs 
Send broadcast event for when-scrolled detective
> VP-6104: Fix scrolling for catalog dropdown

- src/VirtoCommerce.StoreModule.Web/Localizations/en.VirtoCommerce.Store.json
- src/VirtoCommerce.StoreModule.Web/Scripts/blades/store-detail.js
- src/VirtoCommerce.StoreModule.Web/Scripts/blades/store-detail.tpl.html
- src/VirtoCommerce.StoreModule.Web/Scripts/directives/vaStoreSelector.js
- src/VirtoCommerce.StoreModule.Web/Scripts/directives/vaStoreSelector.tpl.html
https://virtocommerce.atlassian.net/browse/VP-6717
> VP-6717: Add vaStoreSelector and use it in store-details blade

- src/VirtoCommerce.StoreModule.Web/Scripts/blades/store-detail.js
- src/VirtoCommerce.StoreModule.Web/Scripts/blades/stores-list.js
> VP-6366: Replace panel action icons

- src/VirtoCommerce.StoreModule.Web/Scripts/widgets/assetsWidget.tpl.html
- src/VirtoCommerce.StoreModule.Web/Scripts/widgets/storeAdvancedWidget.tpl.html
- src/VirtoCommerce.StoreModule.Web/Scripts/widgets/storeNotificationsLogWidget.tpl.html
- src/VirtoCommerce.StoreModule.Web/Scripts/widgets/storeNotificationsWidget.tpl.html
> VP-6648: Add icons to widgets inside store settings blade

- src/VirtoCommerce.StoreModule.Web/Scripts/directives/vaStoreSelector.js
- src/VirtoCommerce.StoreModule.Web/Scripts/directives/vaStoreSelector.tpl.html
Ability to disable va-store-selector.
More about the directive: https://virtocommerce.atlassian.net/browse/VP-6717
> VP-6748: Add "disabled" feature to va-store-selector

- src/VirtoCommerce.StoreModule.Web/Scripts/blades/store-advanced.js
- src/VirtoCommerce.StoreModule.Web/Scripts/blades/store-detail.js
- src/VirtoCommerce.StoreModule.Web/Scripts/blades/stores-list.js
> VP-6768 Security section Replace Key icon

- src/VirtoCommerce.StoreModule.Web/Scripts/blades/store-detail.js
Also, this prevents a flickering of dropped down combobox contents.
> VP-6757: Allow to edit store when previously set catalog was deleted

- src/VirtoCommerce.StoreModule.Web/Scripts/blades/store-detail.js
There are strange issues due to the order of returning values (flickering, etc...). Just made calls in sync.
> VP-6757: Repair catalogs loading

- src/VirtoCommerce.StoreModule.Web/Module.cs
https://virtocommerce.atlassian.net/browse/VP-6905
> VP-6905 remove call to BuildServiceProvider

- src/VirtoCommerce.StoreModule.Data/Services/StoreNotificationSender.cs
https://virtocommerce.atlassian.net/browse/VP-6892
LinkGenerator unsures correct token encoding in URL.
> VP-6892: Use LinkGenerator for EmailVerificationLink

- tests/VirtoCommerce.StoreModule.Tests/StoreNotificationSenderUnitTests.cs
Cover StoreNotificationSender scenarios https://virtocommerce.atlassian.net/browse/VP-6892
https://virtocommerce.atlassian.net/browse/VP-7240
> VP-7240: Add StoreNotificationSenderUnitTests

- src/VirtoCommerce.StoreModule.Web/Localizations/en.VirtoCommerce.Store.json
- src/VirtoCommerce.StoreModule.Web/Scripts/store.js
- src/VirtoCommerce.StoreModule.Web/module.manifest
https://virtocommerce.atlassian.net/browse/PT-945
> PT-946: Resolve URL for login on behalf from store

- src/VirtoCommerce.StoreModule.Web/Scripts/blades/store-advanced.tpl.html
- src/VirtoCommerce.StoreModule.Web/module.manifest
https://virtocommerce.atlassian.net/browse/PT-1895
> PT-1895: Display localized country name in UI

- src/VirtoCommerce.StoreModule.Web/Controllers/Api/StoreModuleController.cs
https://virtocommerce.atlassian.net/browse/PT-2933
> PT-2935: Fix send StoreDynamicEmailNotification

- src/VirtoCommerce.StoreModule.Core/ModuleConstants.cs
> PT-1924: Add EnablePriceRoundingForTotalsCalculation setting

- docs/index.md
> PT-1924: Update docs

- .gitignore
- src/VirtoCommerce.StoreModule.Core/Events/StoreChangeEvent.cs
- src/VirtoCommerce.StoreModule.Core/Services/IStoreSearchService.cs
- src/VirtoCommerce.StoreModule.Core/Services/IStoreService.cs
- src/VirtoCommerce.StoreModule.Core/VirtoCommerce.StoreModule.Core.csproj
- src/VirtoCommerce.StoreModule.Data/ExportImport/StoreExportImport.cs
- src/VirtoCommerce.StoreModule.Data/Model/StoreEntity.cs
- src/VirtoCommerce.StoreModule.Data/Repositories/IStoreRepository.cs
- src/VirtoCommerce.StoreModule.Data/Repositories/StoreRepository.cs
- src/VirtoCommerce.StoreModule.Data/Services/StoreNotificationSender.cs
- src/VirtoCommerce.StoreModule.Data/Services/StoreSearchService.cs
- src/VirtoCommerce.StoreModule.Data/Services/StoreService.cs
- src/VirtoCommerce.StoreModule.Data/VirtoCommerce.StoreModule.Data.csproj
- src/VirtoCommerce.StoreModule.Web/Controllers/Api/StoreModuleController.cs
- src/VirtoCommerce.StoreModule.Web/ExportImport/StoreExportImport.cs
- src/VirtoCommerce.StoreModule.Web/module.manifest
- tests/VirtoCommerce.StoreModule.Tests/StoreNotificationSenderTests.cs
- tests/VirtoCommerce.StoreModule.Tests/StoreServiceUnitTest.cs
> PT-2263: Update store module

- src/VirtoCommerce.StoreModule.Web/Controllers/Api/StoreModuleController.cs
After sending dynamic notification user sees error in admin
https://virtocommerce.atlassian.net/browse/PT-5124
> PT-5124: After sending dynamic notification user sees error in admin

- src/VirtoCommerce.StoreModule.Web/Scripts/blades/store-detail.js
> PT-3807: Fix reset button

- .github/workflows/main.yml
- .github/workflows/publish_nugets.yml
- Directory.Build.props
- src/VirtoCommerce.StoreModule.Core/VirtoCommerce.StoreModule.Core.csproj
- src/VirtoCommerce.StoreModule.Data/Repositories/StoreDbContext.cs
- src/VirtoCommerce.StoreModule.Data/VirtoCommerce.StoreModule.Data.csproj
- src/VirtoCommerce.StoreModule.Web/Module.cs
- src/VirtoCommerce.StoreModule.Web/VirtoCommerce.StoreModule.Web.csproj
- src/VirtoCommerce.StoreModule.Web/module.manifest
- tests/VirtoCommerce.StoreModule.Tests/VirtoCommerce.StoreModule.Tests.csproj
Bump .Net and EF up to 6
https://virtocommerce.atlassian.net/browse/PT-1956
>  PT-1956: Bump .Net and EF up to 6

- src/VirtoCommerce.StoreModule.Core/Services/IStoreCurrencyResolver.cs
- src/VirtoCommerce.StoreModule.Data/Caching/StoreCurrencyCacheRegion.cs
- src/VirtoCommerce.StoreModule.Data/Services/StoreCurrencyResolver.cs
- src/VirtoCommerce.StoreModule.Data/VirtoCommerce.StoreModule.Data.csproj
- src/VirtoCommerce.StoreModule.Web/Module.cs
Store currency service is moved from the xApi module
https://virtocommerce.atlassian.net/browse/PT-5343
> PT-5343: Store currency service is moved from the xApi module

- src/VirtoCommerce.StoreModule.Web/Localizations/en.VirtoCommerce.Store.json
- src/VirtoCommerce.StoreModule.Web/module.manifest
Added Localization for EnablePriceRoundingForTotalsCalculation setting.
https://virtocommerce.atlassian.net/browse/PT-6116
> Added Localization for EnablePriceRoundingForTotalsCalculation setting.

- src/VirtoCommerce.StoreModule.Web/Localizations/en.VirtoCommerce.Store.json
Corrected errors and rewrote some phrases in the EN loc file
> dos: Fix language in the localization file

- src/VirtoCommerce.StoreModule.Data/Repositories/StoreRepository.cs
https://virtocommerce.atlassian.net/browse/PT-7983
> PT-7983: Fix repository extensibility (make GetByIdsAsync virtual)

- src/VirtoCommerce.StoreModule.Data/Migrations/20201229104050_UpdateLoginOnBehalf.cs
Add AspNetRoleClaims table existence check to avoid module startup failures when security database have had separated
https://virtocommerce.atlassian.net/browse/PT-8463
> PT-8463: Add AspNetRoleClaims table existence check to avoid module startup failures

- src/VirtoCommerce.StoreModule.Web/Localizations/ru.VirtoCommerce.Store.json
> Updated ru localization

- src/VirtoCommerce.StoreModule.Web/package-lock.json
- src/VirtoCommerce.StoreModule.Web/package.json
- src/VirtoCommerce.StoreModule.Web/webpack.config.js
feat: add nodejs-lts support
https://virtocommerce.atlassian.net/browse/PT-9395
> PT-9395: add nodejs-lts support

- .editorconfig
- Directory.Build.props
- VirtoCommerce.StoreModule.sln.DotSettings
- module.ignore
- src/VirtoCommerce.StoreModule.Core/Notifications/StoreDynamicEmailNotification.cs
- src/VirtoCommerce.StoreModule.Core/Services/IStoreSearchService.cs
- src/VirtoCommerce.StoreModule.Core/Services/IStoreService.cs
- src/VirtoCommerce.StoreModule.Core/VirtoCommerce.StoreModule.Core.csproj
- src/VirtoCommerce.StoreModule.Data.MySql/VirtoCommerce.StoreModule.Data.MySql.csproj
- src/VirtoCommerce.StoreModule.Data.PostgreSql/VirtoCommerce.StoreModule.Data.PostgreSql.csproj
- src/VirtoCommerce.StoreModule.Data.SqlServer/VirtoCommerce.StoreModule.Data.SqlServer.csproj
- src/VirtoCommerce.StoreModule.Data/ExportImport/StoreExportImport.cs
- src/VirtoCommerce.StoreModule.Data/Repositories/IStoreRepository.cs
- src/VirtoCommerce.StoreModule.Data/Repositories/StoreRepository.cs
- src/VirtoCommerce.StoreModule.Data/Services/StoreCurrencyResolver.cs
- src/VirtoCommerce.StoreModule.Data/Services/StoreNotificationSender.cs
- src/VirtoCommerce.StoreModule.Data/Services/StoreSearchService.cs
- src/VirtoCommerce.StoreModule.Data/Services/StoreService.cs
- src/VirtoCommerce.StoreModule.Data/VirtoCommerce.StoreModule.Data.csproj
- src/VirtoCommerce.StoreModule.Web/Controllers/Api/StoreModuleController.cs
- src/VirtoCommerce.StoreModule.Web/ExportImport/StoreExportImport.cs
- src/VirtoCommerce.StoreModule.Web/Module.cs
- src/VirtoCommerce.StoreModule.Web/VirtoCommerce.StoreModule.Web.csproj
- src/VirtoCommerce.StoreModule.Web/module.manifest
- tests/VirtoCommerce.StoreModule.Tests/StoreNotificationSenderTests.cs
- tests/VirtoCommerce.StoreModule.Tests/StoreServiceUnitTest.cs
- tests/VirtoCommerce.StoreModule.Tests/VirtoCommerce.StoreModule.Tests.csproj
https://virtocommerce.atlassian.net/browse/PT-10449
> PT-10449: Update Crud and Search services

- src/VirtoCommerce.StoreModule.Core/ModuleConstants.cs
- src/VirtoCommerce.StoreModule.Web/Localizations/en.VirtoCommerce.Store.json
https://virtocommerce.atlassian.net/browse/PT-12829
> PT-12829: add EmailVerificationRequired setting

- src/VirtoCommerce.StoreModule.Web/Localizations/en.VirtoCommerce.Store.json
- src/VirtoCommerce.StoreModule.Web/Localizations/ru.VirtoCommerce.Store.json
https://virtocommerce.atlassian.net/browse/PT-13817
> PT-13817: add line break

- src/VirtoCommerce.StoreModule.Web/ExportImport/StoreExportImport.cs
fix: Sonar Warning. Change this condition so that it does not always evaluate to True.
https://virtocommerce.atlassian.net/browse/PT-13839
> PT-13839: Change this condition so that it does not always evaluate to True

- .nuke
- .nuke/parameters.json
- Directory.Build.props
- src/VirtoCommerce.StoreModule.Core/VirtoCommerce.StoreModule.Core.csproj
- src/VirtoCommerce.StoreModule.Data.MySql/VirtoCommerce.StoreModule.Data.MySql.csproj
- src/VirtoCommerce.StoreModule.Data.PostgreSql/VirtoCommerce.StoreModule.Data.PostgreSql.csproj
- src/VirtoCommerce.StoreModule.Data.SqlServer/VirtoCommerce.StoreModule.Data.SqlServer.csproj
- src/VirtoCommerce.StoreModule.Data/Repositories/StoreDbContext.cs
- src/VirtoCommerce.StoreModule.Data/Services/StoreNotificationSender.cs
- src/VirtoCommerce.StoreModule.Data/VirtoCommerce.StoreModule.Data.csproj
- src/VirtoCommerce.StoreModule.Web/VirtoCommerce.StoreModule.Web.csproj
- src/VirtoCommerce.StoreModule.Web/module.manifest
- src/VirtoCommerce.StoreModule.Web/package-lock.json
- tests/VirtoCommerce.StoreModule.Tests/StoreServiceUnitTest.cs
- tests/VirtoCommerce.StoreModule.Tests/VirtoCommerce.StoreModule.Tests.csproj
https://virtocommerce.atlassian.net/browse/PT-14740
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Store_3.800.0-pr-128-e64a.zip
> PT-14740: update to .NET8

- src/VirtoCommerce.StoreModule.Web/Scripts/blades/stores-list.tpl.html
feat: Remove Counter from Search panel
https://virtocommerce.atlassian.net/browse/VCST-972
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Store_3.801.0-pr-131-b358.zip
> VCST-972: Remove Counter from Search panel

- src/VirtoCommerce.StoreModule.Web/Authorization/StoreAuthorizationHandler.cs
- src/VirtoCommerce.StoreModule.Web/Controllers/Api/StoreModuleController.cs
- src/VirtoCommerce.StoreModule.Web/module.manifest
fix: Store scopes are not working for API GET stores/{id}
https://virtocommerce.atlassian.net/browse/VCST-1129
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Store_3.802.0-pr-132-2ebe.zip
> VCST-1129: Store scopes are not working

- src/VirtoCommerce.StoreModule.Core/Model/ModulePublicStoreSettings.cs
- src/VirtoCommerce.StoreModule.Core/Model/PublicStoreSetting.cs
- src/VirtoCommerce.StoreModule.Core/Services/IPublicStoreSettings.cs
- src/VirtoCommerce.StoreModule.Data/Services/PublicStoreSettings.cs
- src/VirtoCommerce.StoreModule.Web/Controllers/Api/StoreModuleController.cs
- src/VirtoCommerce.StoreModule.Web/Module.cs
feat: Adds Public Store Settings REST API /api/stores/{storeid}/public-settings.
feat: Adds IPublicStoreSettings interface. The interface has been introduced to standardize resolving and retrieving public store settings.
https://virtocommerce.atlassian.net/browse/VCST-1427
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Store_3.805.0-pr-134-3f19.zip
> VCSY-1427:  Enhanced Public Store Settings

- src/VirtoCommerce.StoreModule.Data/Services/StoreAuthenticationService.cs
https://virtocommerce.atlassian.net/browse/VCST-1656
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Store_3.807.0-pr-136-2ec3.zip
> VCST-1656: switch to SignInManager factory

- src/VirtoCommerce.StoreModule.Web/Localizations/ru.VirtoCommerce.Store.json
Consistent store settings descriptions in Russian
Artifact URL:
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Store_3.808.0-pr-140-b5c9.zip
> VCST-1854: Update ru.VirtoCommerce.Store.json

- src/VirtoCommerce.StoreModule.Web/Localizations/de.VirtoCommerce.Store.json
Consistent store settings descriptions in German
Artifact URL:
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Store_3.808.0-pr-139-7b18.zip
> VCST-1854: Update de.VirtoCommerce.Store.json

- src/VirtoCommerce.StoreModule.Web/Localizations/en.VirtoCommerce.Store.json
Consistent store settings descriptions
Artifact URL:
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Store_3.808.0-pr-138-1be6.zip
> VCST-1854: Update en.VirtoCommerce.Store.json

- src/VirtoCommerce.StoreModule.Web/Localizations/de.VirtoCommerce.Store.json
- src/VirtoCommerce.StoreModule.Web/Localizations/en.VirtoCommerce.Store.json
- src/VirtoCommerce.StoreModule.Web/Localizations/es.VirtoCommerce.Store.json
- src/VirtoCommerce.StoreModule.Web/Localizations/fr.VirtoCommerce.Store.json
- src/VirtoCommerce.StoreModule.Web/Localizations/it.VirtoCommerce.Store.json
- src/VirtoCommerce.StoreModule.Web/Localizations/ja.VirtoCommerce.Store.json
- src/VirtoCommerce.StoreModule.Web/Localizations/pl.VirtoCommerce.Store.json
- src/VirtoCommerce.StoreModule.Web/Localizations/pt.VirtoCommerce.Store.json
- src/VirtoCommerce.StoreModule.Web/Localizations/ru.VirtoCommerce.Store.json
- src/VirtoCommerce.StoreModule.Web/Localizations/zh.VirtoCommerce.Store.json
Added localization files in French. Spanish, Portugese, Polish, Italian, Chinese, Japanese. updated files in English, German, Russian
Artifact URL:
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Store_3.810.0-pr-142-3b0f.zip
> VCST-1993: Add localization

- src/VirtoCommerce.StoreModule.Web/Localizations/de.VirtoCommerce.Store.json
Localization corrections. Geschäft replaced with Shop
https://virtocommerce.atlassian.net/browse/VCST-1876
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Store_3.812.0-pr-144-18e4.zip
> Localization corrections

- src/VirtoCommerce.StoreModule.Core/Extensions/SeoExtensions.cs
- src/VirtoCommerce.StoreModule.Core/Extensions/StoreExtensions.cs
- src/VirtoCommerce.StoreModule.Core/ModuleConstants.cs
- src/VirtoCommerce.StoreModule.Web/module.manifest
- tests/VirtoCommerce.StoreModule.Tests/SeoExtensionsTests.cs
- tests/VirtoCommerce.StoreModule.Tests/VirtoCommerce.StoreModule.Tests.csproj
https://virtocommerce.atlassian.net/browse/VCST-2821
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Store_3.813.0-pr-147-f20c.zip
> VCST-2821: Move SEO extensions from VirtoCommerce.Tools

- src/VirtoCommerce.StoreModule.Core/Services/IStoreService.cs
- src/VirtoCommerce.StoreModule.Core/VirtoCommerce.StoreModule.Core.csproj
- src/VirtoCommerce.StoreModule.Data.MySql/Migrations/20250515143359_AddIndexForOuterId.Designer.cs
- src/VirtoCommerce.StoreModule.Data.MySql/Migrations/20250515143359_AddIndexForOuterId.cs
- src/VirtoCommerce.StoreModule.Data.MySql/Migrations/StoreDbContextModelSnapshot.cs
- src/VirtoCommerce.StoreModule.Data.MySql/VirtoCommerce.StoreModule.Data.MySql.csproj
- src/VirtoCommerce.StoreModule.Data.PostgreSql/Migrations/20250515143347_AddIndexForOuterId.Designer.cs
- src/VirtoCommerce.StoreModule.Data.PostgreSql/Migrations/20250515143347_AddIndexForOuterId.cs
- src/VirtoCommerce.StoreModule.Data.PostgreSql/Migrations/StoreDbContextModelSnapshot.cs
- src/VirtoCommerce.StoreModule.Data.PostgreSql/VirtoCommerce.StoreModule.Data.PostgreSql.csproj
- src/VirtoCommerce.StoreModule.Data.SqlServer/Migrations/20250515143325_AddIndexForOuterId.Designer.cs
- src/VirtoCommerce.StoreModule.Data.SqlServer/Migrations/20250515143325_AddIndexForOuterId.cs
- src/VirtoCommerce.StoreModule.Data.SqlServer/VirtoCommerce.StoreModule.Data.SqlServer.csproj
- src/VirtoCommerce.StoreModule.Data/Model/SeoInfoEntity.cs
- src/VirtoCommerce.StoreModule.Data/Model/StoreEntity.cs
- src/VirtoCommerce.StoreModule.Data/Repositories/StoreDbContext.cs
- src/VirtoCommerce.StoreModule.Data/Services/StoreCurrencyResolver.cs
- src/VirtoCommerce.StoreModule.Data/Services/StoreService.cs
- src/VirtoCommerce.StoreModule.Data/VirtoCommerce.StoreModule.Data.csproj
- src/VirtoCommerce.StoreModule.Web/Controllers/Api/StoreModuleController.cs
- src/VirtoCommerce.StoreModule.Web/module.manifest
GET /api/stores/outer/{outerId}
https://virtocommerce.atlassian.net/browse/VCST-3154
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Store_3.816.0-pr-150-e6dc.zip
> VCST-3154: Extend Rest API with GetByOuterId

- src/VirtoCommerce.StoreModule.Web/Scripts/blades/templates/accountDetails/storeId.html
- src/VirtoCommerce.StoreModule.Web/Scripts/directives/vaStoreSelector.js
https://virtocommerce.atlassian.net/browse/VCST-3560
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Store_3.820.0-pr-154-ea0a.zip
> VCST-3560: Fix store selector
